import "next/dist/server/node-environment-baseline";
import { isNextRouterError } from "next/dist/client/components/is-next-router-error.js";
import type { CacheNodeSeedData, FlightDataPath } from "next/dist/shared/lib/app-router-types";
import { cloneElement, createElement, isValidElement, type ReactElement, type ReactNode } from "react";
import type { RenderConfiguration } from "../testing-library";
import {
  cleanup as baseCleanup,
  initialize as baseInitialize,
  renderServer as baseRenderServer,
} from "../testing-library";
import { NextRouter } from "vitest-plugin-rsc/nextjs/client";
import { buildFlightRouterStateWithNext } from "./flight-router-state";
import {
  createNextRequestContext,
  resetNextRequestContextCache,
  type NextRequestContextOptions,
} from "./request-context";

export * from "../testing-library";

export type NextRenderConfiguration = Partial<RenderConfiguration> & {
  serverActionsViaMsw?: boolean;
};

let config: NextRenderConfiguration = {
  serverActionsViaMsw: false,
};

export function initialize(customConfig: NextRenderConfiguration = {}): void {
  config = {
    ...config,
    ...customConfig,
  };
  baseInitialize({
    serverActionCaller: config.serverActionsViaMsw
      ? "vitest-plugin-rsc/nextjs/testing-library-client"
      : undefined,
    rootOptions: {
      onCaughtError: (error) => {
        if (isNextRouterError(error)) return;
        console.log(error);
      },
      ...(customConfig.rootOptions ?? {}),
    },
    ...config,
  });
}

export { NextRouter } from "vitest-plugin-rsc/nextjs/client";

type BaseRenderServerOptions = NonNullable<Parameters<typeof baseRenderServer>[1]>;

export async function renderServer(
  ui: ReactNode,
  { url = "/", headers, ...options }: BaseRenderServerOptions & NextRequestContextOptions = {},
) {
  const serverContext = await createNextRequestContext({ url, headers });
  let routerRefreshVersion = 0;
  return baseRenderServer(ui, {
    ...options,
    serverContext: {
      run: serverContext.run,
      prepareRoot: ({ root, actionRequest }) => {
        if (!config.serverActionsViaMsw && actionRequest) {
          routerRefreshVersion += 1;
        }
        return withNextRouterInitialTree(root, url, routerRefreshVersion);
      },
      completeAction: config.serverActionsViaMsw
        ? serverContext.completeAction
        : () => ({ shouldRender: true }),
      createActionResponse: config.serverActionsViaMsw
        ? ({ root, returnValue, shouldRender }) =>
            createNextActionResponse(root, returnValue, shouldRender)
        : undefined,
    },
  });
}

async function createNextActionResponse(root: ReactNode, returnValue: unknown, shouldRender: boolean) {
  const nextRouter = findNextRouterElement(root);
  if (!shouldRender || !nextRouter) {
    return { a: returnValue, f: "", q: "", i: false };
  }

  const props = nextRouter.props as {
    children: ReactNode;
    route?: string;
    url?: string;
  };
  const url = props.url ?? "/";
  const route = props.route ?? url;
  const location = new URL(url, "http://localhost");
  const tree = await buildFlightRouterStateWithNext(route, location.pathname, location.search);
  const seedData: CacheNodeSeedData = [props.children, {}, null, false, null];

  // Next's action handler sends an action result plus Flight data generated by
  // the private app-render pipeline. We cannot import that whole request
  // handler for component tests, so this builds the minimal response shape that
  // Next's server-action reducer consumes after the action POST:
  // https://github.com/vercel/next.js/blob/938c286bac984aa7275bb4c18aa0c154b443aa93/packages/next/src/server/app-render/action-handler.ts#L1160-L1225
  // https://github.com/vercel/next.js/blob/938c286bac984aa7275bb4c18aa0c154b443aa93/packages/next/src/client/components/router-reducer/reducers/server-action-reducer.ts#L246-L299
  return {
    a: returnValue,
    f: [[tree, seedData, null, false] satisfies FlightDataPath],
    q: location.search,
    i: false,
  };
}

async function withNextRouterInitialTree(
  node: ReactNode,
  defaultUrl: string,
  routerRefreshVersion: number,
): Promise<ReactNode> {
  if (!findNextRouterElement(node)) {
    const location = new URL(defaultUrl, "http://localhost");
    return createElement(
      NextRouter,
      {
        key: routerRefreshVersion,
        url: defaultUrl,
        route: location.pathname,
        initialTree: await buildFlightRouterStateWithNext(
          location.pathname,
          location.pathname,
          location.search,
        ),
      },
      node,
    );
  }

  return injectNextRouterInitialTree(node, routerRefreshVersion);
}

async function injectNextRouterInitialTree(
  node: ReactNode,
  routerRefreshVersion: number,
): Promise<ReactNode> {
  if (Array.isArray(node)) {
    return Promise.all(node.map((child) => injectNextRouterInitialTree(child, routerRefreshVersion)));
  }

  if (!isValidElement(node)) return node;

  if (isNextRouterElement(node)) {
    const props = node.props as {
      children?: ReactNode;
      route?: string;
      url?: string;
    };
    const url = props.url ?? "/";
    const route = props.route ?? url;
    const location = new URL(url, "http://localhost");
    return cloneElement(node as ReactElement<{ initialTree?: unknown }>, {
      key: routerRefreshVersion,
      initialTree: await buildFlightRouterStateWithNext(route, location.pathname, location.search),
    });
  }

  const props = node.props as { children?: ReactNode };
  if (!props.children) return node;

  return cloneElement(node as ReactElement<{ children?: ReactNode }>, {
    children: await injectNextRouterInitialTree(props.children, routerRefreshVersion),
  });
}

function findNextRouterElement(node: ReactNode): ReactElement | undefined {
  if (Array.isArray(node)) {
    for (const child of node) {
      const found = findNextRouterElement(child);
      if (found) return found;
    }
    return;
  }

  if (!isValidElement(node)) return;
  if (isNextRouterElement(node)) {
    return node;
  }

  return findNextRouterElement((node.props as { children?: ReactNode }).children);
}

function isNextRouterElement(node: ReactElement) {
  return (
    node.type === NextRouter ||
    (node.type as { $$vitestPluginRscNextRouter?: true }).$$vitestPluginRscNextRouter ||
    (node.type as { $$id?: string }).$$id?.endsWith("#NextRouter")
  );
}

export async function cleanup() {
  await baseCleanup();
  await resetNextRequestContextCache();
}

// @ts-ignore
const expect = globalThis[Symbol.for("expect-global")];

export async function expectToHaveBeenNavigatedTo(url: Partial<URL>) {
  expect(globalThis.onNavigate).toHaveBeenCalledWith(expect.objectContaining(url));
}
