import "next/dist/server/node-environment-baseline";
import { isNextRouterError } from "next/dist/client/components/is-next-router-error.js";
import { urlToUrlWithoutFlightMarker } from "next/dist/client/route-params.js";
import type {
  CacheNodeSeedData,
  FlightDataPath,
  FlightRouterState,
  NavigationFlightResponse,
} from "next/dist/shared/lib/app-router-types";
import {
  cloneElement,
  createElement,
  isValidElement,
  type ReactElement,
  type ReactNode,
} from "react";
import type { RenderConfiguration } from "../testing-library";
import {
  cleanup as baseCleanup,
  initialize as baseInitialize,
  renderServer as baseRenderServer,
} from "../testing-library";
import { NextRouter } from "vitest-plugin-rsc/nextjs/client";
import { buildFlightRouterStateWithNext } from "./flight-router-state";
import {
  createNextRequestContext,
  resetNextRequestContextCache,
  type NextRequestContextOptions,
} from "./request-context";

export * from "../testing-library";

export type NextRenderConfiguration = Partial<RenderConfiguration> & {
  serverActionsViaMsw?: boolean;
};

let config: NextRenderConfiguration = {
  serverActionsViaMsw: false,
};

export function initialize(customConfig: NextRenderConfiguration = {}): void {
  config = {
    ...config,
    ...customConfig,
  };
  baseInitialize({
    serverActionCaller: config.serverActionsViaMsw
      ? "vitest-plugin-rsc/nextjs/testing-library-client"
      : undefined,
    rootOptions: {
      onCaughtError: (error) => {
        if (isNextRouterError(error)) return;
        console.log(error);
      },
      ...(customConfig.rootOptions ?? {}),
    },
    ...config,
  });
}

export { NextRouter } from "vitest-plugin-rsc/nextjs/client";

type BaseRenderServerOptions = NonNullable<Parameters<typeof baseRenderServer>[1]>;

export async function renderServer(
  ui: ReactNode,
  { url = "/", headers, ...options }: BaseRenderServerOptions & NextRequestContextOptions = {},
) {
  const serverContext = await createNextRequestContext({ url, headers });
  return baseRenderServer(ui, {
    ...options,
    serverContext: {
      run: serverContext.run,
      prepareRoot: ({ root }) => withNextRouterInitialTree(root, url),
      completeAction: config.serverActionsViaMsw
        ? serverContext.completeAction
        : () => ({ shouldRender: true }),
      createActionResponse: config.serverActionsViaMsw
        ? ({ root, returnValue, shouldRender }) =>
            createNextActionResponse(root, returnValue, shouldRender)
        : undefined,
      createRouteResponse: ({ root, request }) =>
        createNextRouteResponse(root, request.url, request.routerState),
    },
  });
}

async function createNextRouteResponse(
  root: ReactNode,
  url: string,
  routerState?: string | null,
): Promise<NavigationFlightResponse> {
  const nextRouter = findNextRouterElement(root);
  if (!nextRouter) {
    return { f: [], q: new URL(url).search, i: false, S: false, h: null };
  }

  const props = nextRouter.props as {
    children: ReactNode;
    route?: string;
    url?: string;
  };
  const location = urlToUrlWithoutFlightMarker(new URL(url));
  const route = props.route ?? props.url ?? location.pathname;
  const tree =
    parseRequestedFlightRouterState(routerState) ??
    (await buildFlightRouterStateWithNext(route, location.pathname, location.search));
  const seedData = createSeedDataFromFlightRouterState(tree, props.children);

  // Next compares this response build id to its initialized navigation build
  // id before writing dynamic data into the router cache:
  // https://github.com/vercel/next.js/blob/938c286bac984aa7275bb4c18aa0c154b443aa93/packages/next/src/client/components/router-reducer/fetch-server-response.ts#L266-L270
  return {
    b: "",
    f: [[tree, seedData, null, false] satisfies FlightDataPath],
    q: location.search,
    i: false,
    S: false,
    h: null,
  };
}

async function createNextActionResponse(
  root: ReactNode,
  returnValue: unknown,
  shouldRender: boolean,
) {
  const nextRouter = findNextRouterElement(root);
  if (!shouldRender || !nextRouter) {
    return { a: returnValue, f: "", q: "", i: false };
  }

  const props = nextRouter.props as {
    children: ReactNode;
    route?: string;
    url?: string;
  };
  const url = props.url ?? "/";
  const route = props.route ?? url;
  const location = new URL(url, "http://localhost");
  const tree = await buildFlightRouterStateWithNext(route, location.pathname, location.search);
  const seedData = createSeedDataFromFlightRouterState(tree, props.children);

  // Next's action handler sends an action result plus Flight data generated by
  // the private app-render pipeline. We cannot import that whole request
  // handler for component tests, so this builds the minimal response shape that
  // Next's server-action reducer consumes after the action POST:
  // https://github.com/vercel/next.js/blob/938c286bac984aa7275bb4c18aa0c154b443aa93/packages/next/src/server/app-render/action-handler.ts#L1160-L1225
  // https://github.com/vercel/next.js/blob/938c286bac984aa7275bb4c18aa0c154b443aa93/packages/next/src/client/components/router-reducer/reducers/server-action-reducer.ts#L246-L299
  return {
    b: "",
    a: returnValue,
    f: [[tree, seedData, null, false] satisfies FlightDataPath],
    q: location.search,
    i: false,
  };
}

async function withNextRouterInitialTree(node: ReactNode, defaultUrl: string): Promise<ReactNode> {
  if (!findNextRouterElement(node)) {
    const location = new URL(defaultUrl, "http://localhost");
    const Router = NextRouter as (props: {
      children?: ReactNode;
      route?: string;
      url?: string;
      initialTree?: FlightRouterState;
    }) => ReactElement | null;

    return createElement(
      Router,
      {
        url: defaultUrl,
        route: location.pathname,
        initialTree: await buildFlightRouterStateWithNext(
          location.pathname,
          location.pathname,
          location.search,
        ),
      },
      node,
    );
  }

  return injectNextRouterInitialTree(node);
}

async function injectNextRouterInitialTree(node: ReactNode): Promise<ReactNode> {
  if (Array.isArray(node)) {
    return Promise.all(node.map((child) => injectNextRouterInitialTree(child)));
  }

  if (!isValidElement(node)) return node;

  if (isNextRouterElement(node)) {
    const props = node.props as {
      children?: ReactNode;
      route?: string;
      url?: string;
    };
    const url = props.url ?? "/";
    const route = props.route ?? url;
    const location = new URL(url, "http://localhost");
    return cloneElement(node as ReactElement<{ initialTree?: unknown }>, {
      initialTree: await buildFlightRouterStateWithNext(route, location.pathname, location.search),
    });
  }

  const props = node.props as { children?: ReactNode };
  if (!props.children) return node;

  return cloneElement(node as ReactElement<{ children?: ReactNode }>, {
    children: await injectNextRouterInitialTree(props.children),
  });
}

function findNextRouterElement(node: ReactNode): ReactElement | undefined {
  if (Array.isArray(node)) {
    for (const child of node) {
      const found = findNextRouterElement(child);
      if (found) return found;
    }
    return;
  }

  if (!isValidElement(node)) return;
  if (isNextRouterElement(node)) {
    return node;
  }

  return findNextRouterElement((node.props as { children?: ReactNode }).children);
}

function isNextRouterElement(node: ReactElement) {
  return (
    node.type === NextRouter ||
    (node.type as { $$vitestPluginRscNextRouter?: true }).$$vitestPluginRscNextRouter ||
    (node.type as { $$id?: string }).$$id?.endsWith("#NextRouter")
  );
}

function createSeedDataFromFlightRouterState(
  tree: FlightRouterState,
  children: ReactNode,
): CacheNodeSeedData {
  const parallelRoutes: CacheNodeSeedData[1] = {};
  for (const [parallelRouteKey, childTree] of Object.entries(tree[1])) {
    parallelRoutes[parallelRouteKey] = createSeedDataFromFlightRouterState(childTree, children);
  }

  return [children, parallelRoutes, null, false, null];
}

function parseRequestedFlightRouterState(
  routerState?: string | null,
): FlightRouterState | undefined {
  if (!routerState) return;
  try {
    const tree = JSON.parse(decodeURIComponent(routerState)) as FlightRouterState;
    const result: FlightRouterState = [tree[0], tree[1]];
    if (2 in tree) result[2] = tree[2];
    if (4 in tree) result[4] = tree[4];
    return result;
  } catch {
    return;
  }
}

export async function cleanup() {
  await baseCleanup();
  await resetNextRequestContextCache();
}

// @ts-ignore
const expect = globalThis[Symbol.for("expect-global")];

export async function expectToHaveBeenNavigatedTo(url: Partial<URL>) {
  expect(globalThis.onNavigate).toHaveBeenCalledWith(expect.objectContaining(url));
}
