name: Preview Package

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  preview:
    if: github.repository == 'storybookjs/vitest-plugin-rsc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm dlx pkg-pr-new publish --compact --no-template --pnpm --comment=update --commentWithDev --packageManager=pnpm packages/vitest-plugin-rsc
